// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tategrqxvlqezsuejzmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhdGVncnF4dmxxZXpzdWVqem1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzIxMjAsImV4cCI6MjA3MjY0ODEyMH0.dEHi0hQJ0Aidb3VJ5rCR7wb1lgW7ocHRl1AGd9Ctw0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
